### ISSUE TITLE
repoem機能

### ISSUE THREAD

**Issue by suzan2go** [CWPoemDev/nasulog#115]
repoem誕生秘話。
> あ、引用はいいかも！
コメントって、記事が主、コメントが副、みたいな関係になるので、個人的には引用のほうが広がりを感じる

> 少し考えたんですが、コメント機能はなしにし引用だけで対応するのが良いかなと思ってます。コメントだとそのポエム作成者の意図と関わりなくコメント欄が増えて行ってしまう気がしていて。

**Comment by suzan2go** [comment]
とりあえずこんな感じはどうだろう
![image](https://cloud.githubusercontent.com/assets/8841470/12484306/05040d7c-c09d-11e5-9b62-dcbf3f1bfb1c.png)

**Comment by nasum** [comment]
アイコンと吹き出しは良さそう。位置は上が良いのかな？ポエムをよんだあとリポエムするということを考えると下のような気がする。

**Comment by suzan2go** [comment]
最初右下においたんだけど、ごちゃごちゃ見えてしまったんですよね。特にスマホ画面だと意外と幅がなくて。

下の作者の欄、時間の表示とかもう少しキレイにしてみるか。秒とか+9とかいらないし。

**Comment by nasum** [comment]
時間の所はちょっと横着していて良くなかったですね。それさえ綺麗になればうまく行くようであれば先に時間の所をなんとかしましょうか。

**Comment by suzan2go** [comment]
オッスオッス！

**Comment by nasum** [comment]
issue立てた #117

**Comment by suzan2go** [comment]
どうやろ
![image](https://cloud.githubusercontent.com/assets/8841470/12528131/e10f7304-c1d0-11e5-9d03-3a6a13eea17b.png)

**Comment by nasum** [comment]
操作するボタンが右と左に分かれてるの良くないかも。
読んだよボタンの上あたりにするとごちゃっとしちゃうかな？
あとアイコンだけだと何をする機能なのかわかりにくそう。「リポエム」か「repoem」って単語は横にあると親切かもしれない。

いろいろ言ってすんません(>_<;)

**Comment by suzan2go** [comment]
popoverする感じじゃだめかな？
![image](https://cloud.githubusercontent.com/assets/8841470/12528399/e351712e-c1d7-11e5-8652-705a7722f23f.png)

**Comment by suzan2go** [comment]
そんなに説明的になる必要はないと思うんだけどあったほうがいいかな

以下ベンチマーク
twitter
![image](https://cloud.githubusercontent.com/assets/8841470/12528452/56d412cc-c1d9-11e5-97df-006d56993478.png)
esa
![image](https://cloud.githubusercontent.com/assets/8841470/12528455/6dd0eb6c-c1d9-11e5-976f-5798f97f4af0.png)

**Comment by nasum** [comment]
画像がｗ
Twitterとか我々は慣れてるからわかりますけど、nasulogでそのアイコン出されてわかるかな？っと思ったんですよね。
もちろんリポエムなんて書かれてもぱっとわからないのですが、少なくともこのボタンを押すと「リポエムされる」ってのがわかるんで必要かなと。何も書かれてないとおしづらいかなって。

**Comment by suzan2go** [comment]
> もちろんリポエムなんて書かれてもぱっとわからない

**Comment by suzan2go** [comment]
あとどうでもいいけどRT(リツイート)じゃなくてRP(レポエーム)というのはどうだろう

**Comment by nasum** [comment]
マウスオーバーぐらいで十分ですかね。
RPはとても良いと思います:smile:

**Comment by suzan2go** [comment]
我々が積極的に使って、浸透させていこう

**Comment by nasum** [comment]
それでいきましょう。実装おなしゃす！

**Comment by suzan2go** [comment]
おっすおっすとりあえず作ってデザインはまた、いくつか案出します！
