### ISSUE TITLE
/home と /poems のパス変更

### ISSUE THREAD

**Issue by YusukeIwaki** [CWPoemDev/nasulog#127]
現状

`/home` ・・・（全ユーザの）ポエム一覧
`/poems` ・・・ログインユーザのみに絞ったポエム一覧
`/poems/:id` ・・・（全ユーザの）ポエム詳細

となっているが、たとえば以下のように、よりRESTな設計にしたいかも。

`/poems` ・・・全ユーザのポエム一覧
`/poems/:id` ・・・（全ユーザの）ポエム詳細
`/user/poems` ・・・ログインユーザのみに絞ったポエム一覧

**Comment by suzan2go** [comment]
:+1:

**Comment by suzan2go** [comment]
他の人のポエム一覧もそのうち表示できるようにするなら`/user/:id/poems` でも良いかなと思いました。

この設計になったら、ついでにhome_controllerではログインしてる人にしか見せたくない`Poem` は読み込まず、ログイン前トップ画面をrenderするだけにしたほうが何となく安全な気がする
