### ISSUE TITLE
ポエム削除機能

### ISSUE THREAD

**Issue by nasum** [CWPoemDev/nasulog#129]
そろそろ必要となってきました

**Comment by YusukeIwaki** [comment]
レコード自体を消す？それとも、deletedフラグみたいなのをつけるだけにする？

**Comment by YusukeIwaki** [comment]
あとは、repoemとかも連鎖的に消す？

**Comment by suzan2go** [comment]
repoem先も連鎖的に消した方がよさそうですけど、突然自分のものが消えるとバグっぽく感じるので見せ方は考えた方が良い気もする

**Comment by nasum** [comment]
repoemは消さない方がいいかも。
あと、repoemが消されたときも考慮が必要かな。
