### ISSUE TITLE
読んだよマーク付与を非同期に

### ISSUE THREAD

**Issue by nasum** [CWPoemDev/nasulog#132]
読んだよマーク付与を非同期にしたい

**Comment by YusukeIwaki** [comment]
これは即効でやりましょうか

**Comment by nasum** [comment]
reactが入ってるのでそれでやりたいですね。
連打することを考えるとある程度貯めてからリクエストを送る感じになると思います。そうなるとコントローラ側も変えなくちゃいけないので中程度の重さですかね（感覚）。

**Comment by nasum** [comment]
さっさとやろう。
